### PR TITLE
[FIX] fix for negative scrollOffset

### PR DESCRIPTION
**Pull request by vtripolitakis**
Fixes issue with negative `scrollOffset`
See https://github.com/bvaughn/react-window/issues/6#issuecomment-461083915

### CODE REVIEW

**Comment by vtripolitakis** [comment]
Hello! Any chance this will be merged into the `next` release?

**Comment by bvaughn** [comment]
I dunno. I'll try to find time to look at it soon. Forgot over the weekend. Sorry.

**Comment by vtripolitakis** [comment]
Thanks for the prompt response. If you need any clarification on the rationale of the fix and the side effects that issue is causing, I'm more than happy to share.

**Comment by bvaughn** [comment]
Generally, fixes that are accompanied by unit tests are always easier 😁 but it's cool. Thanks for the offer.

**Comment by bvaughn** [comment]
I would still feel better about merging this PR if it were accompanied by a unit test. I don't suppose you were able to capture the behavior in a test? (or even a more specific repro than "_This happened when I expanded and retracted items and then scrolled to the top having scrollOffset 0 and direction backwards. Then If I expand and retract a few times, I got the negatives._"

**Comment by vtripolitakis** [comment]
Good evening , no I did not get that behavior on a test.
Please have a look here:
http://grvps.nohsys.net:3000/ 
and the code is here (had to take it out of a private repo and strip information)
https://github.com/vtripolitakis/react-window-issue
1. Click toggle All
2. Scroll up and down a few times
3. Click toggle All many times (let's say 10-15)

You'll see that the list gets smaller. If you scroll up and down a little bit all elements appear again.

**Comment by vtripolitakis** [comment]
Good morning!
I see this micro-fix has been approved since 16.03
I'd like to ask you if you plan to merge it into the `next` release in the upcoming days or weeks? 
Our code-base makes heavy use of it, so it would be great it's merged.
Best regards!

**Comment by vtripolitakis** [comment]
Good morning dear Brian,

Any news on this?

Thank you in advance.
Kind regards!

**Comment by bvaughn** [comment]
Hey @vtripolitakis. Thanks again for this PR. This issue was fixed along with a couple of other things as part of a more comprehensive PR #251

**Comment by vtripolitakis** [comment]
Hello @bvaughn !
I checked out and used the `1.9.0-alpha.1` version which actually is branch `issues/6` with the latest merge, to build my example with the problematic behaviour. On the `DynamicSizeList` component the code I patched remains the same and the problem persists.

**Comment by bvaughn** [comment]
My apologies. I guess I got a little too aggressive with cleaning up issues. I have not yet merged the fix from #251 into `DynamicSizeList` (nor the concept of RTL support). I ran out of time yesterday. Will get to it soon.

**Pull request closed without merging**
