### PR TITLE
Fix scroll alignment center calculation

### PR DESCRIPTION
**Pull request by mklinger**

### CODE REVIEW

**Comment by mklinger** [comment]
Fixes #583

**Comment by mariancristivrabie** [comment]
Hi!
Is this PR going to be merged soon?
I have an issue related to the scrollToItem which seems to be fixed by these changes.

**Comment by Brian-McBride** [comment]
Is the project even maintained anymore? It's been over a year since NPM has had a release. 
Seems that more maintainers would help the project to stay current/alive

**Comment by bvaughn** [comment]
> Seems that more maintainers would help the project to stay current/alive

Agreed 😄  Are you interested? I'd love to have a new maintainer or two.

**Pull request closed without merging**
